# Generated by Django 5.2.9 on 2025-12-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='Histoire', max_length=100, unique=True),
        ),
    ]
