# Generated by Django 5.2.9 on 2026-01-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_comment_options_alter_source_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['number'], 'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
        migrations.AddField(
            model_name='article',
            name='vues',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
